#{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "easyauth-proxy.fullname" . }}-ingress
  labels:
    {{- include "easyauth-proxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    -  {{ .Values.appHostName }}
    secretName:  {{ .Values.tlsSecretName }}
  rules:
  - host: {{ .Values.appHostName }}
    http:
      paths:
      - path: {{ .Values.basePath }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "easyauth-proxy.fullname" . }}
            port:
              number: {{ .Values.service.port }}
#{{- end }}